#!/usr/bin/env python3
"""Generate a Composer-compatible autoloader from the vendor tree."""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, "vendor")

psr4, psr0, files, classmap_dirs, excluded = {}, {}, [], [], []


def add_pkg(pkg_dir, cj, rel_base):
    au = cj.get("autoload") or {}
    for ns, paths in (au.get("psr-4") or {}).items():
        if isinstance(paths, str):
            paths = [paths]
        psr4.setdefault(ns, []).extend(
            os.path.normpath(os.path.join(rel_base, p)).replace("\\", "/") for p in paths)
    for ns, paths in (au.get("psr-0") or {}).items():
        if isinstance(paths, str):
            paths = [paths]
        psr0.setdefault(ns, []).extend(
            os.path.normpath(os.path.join(rel_base, p)).replace("\\", "/") for p in paths)
    for f in (au.get("files") or []):
        files.append(os.path.normpath(os.path.join(rel_base, f)).replace("\\", "/"))
    for d in (au.get("classmap") or []):
        classmap_dirs.append(os.path.normpath(os.path.join(rel_base, d)).replace("\\", "/"))
    for d in (au.get("exclude-from-classmap") or []):
        excluded.append(os.path.normpath(os.path.join(rel_base, d)).replace("\\", "/"))


# root package
root_cj = json.load(open(os.path.join(ROOT, "composer.json")))
add_pkg(ROOT, root_cj, ".")

providers, aliases = [], {}
# Laravel's PackageManifest expects the manifest keyed by package name, with
# each entry holding that package's own providers/aliases.
package_manifest = {}

for vendor_name in sorted(os.listdir(VENDOR)):
    vpath = os.path.join(VENDOR, vendor_name)
    if not os.path.isdir(vpath) or vendor_name.startswith("."):
        continue
    for pkg in sorted(os.listdir(vpath)):
        pdir = os.path.join(vpath, pkg)
        cjp = os.path.join(pdir, "composer.json")
        if not os.path.exists(cjp):
            continue
        try:
            cj = json.load(open(cjp))
        except Exception:
            continue
        add_pkg(pdir, cj, f"vendor/{vendor_name}/{pkg}")
        laravel = ((cj.get("extra") or {}).get("laravel") or {})
        pkg_providers = list(laravel.get("providers") or [])
        pkg_aliases = dict(laravel.get("aliases") or {})

        if pkg_providers or pkg_aliases:
            entry = {}
            if pkg_providers:
                entry["providers"] = pkg_providers
            if pkg_aliases:
                entry["aliases"] = pkg_aliases
            package_manifest[cj.get("name") or f"{vendor_name}/{pkg}"] = entry

        providers.extend(pkg_providers)
        aliases.update(pkg_aliases)

# ---- build classmap by scanning classmap dirs ----
CLASS_RE = re.compile(
    rb"^\s*(?:final\s+|abstract\s+|readonly\s+)*(class|interface|trait|enum)\s+([A-Za-z_\x80-\xff][\w\x80-\xff]*)",
    re.M)
NS_RE = re.compile(rb"^\s*namespace\s+([^;{\s]+)", re.M)

classmap = {}
for d in classmap_dirs:
    absd = os.path.join(ROOT, d)
    if os.path.isfile(absd):
        targets = [absd]
    elif os.path.isdir(absd):
        targets = []
        for dp, dn, fn in os.walk(absd):
            dn[:] = [x for x in dn if x not in (".git", "node_modules", "tests", "Tests")]
            targets += [os.path.join(dp, f) for f in fn if f.endswith(".php")]
    else:
        continue
    for t in targets:
        rel = os.path.relpath(t, ROOT).replace("\\", "/")
        if any(rel.startswith(x) for x in excluded):
            continue
        try:
            src = open(t, "rb").read()
        except Exception:
            continue
        nsm = NS_RE.search(src)
        ns = (nsm.group(1).decode() + "\\") if nsm else ""
        for kind, cname in CLASS_RE.findall(src):
            fqcn = ns + cname.decode()
            classmap.setdefault(fqcn, rel)

def php_arr(d, indent="    "):
    out = []
    for k, v in sorted(d.items()):
        if isinstance(v, list):
            inner = ", ".join("$baseDir . '/%s'" % (x[2:] if x.startswith("./") else x) for x in v)
            out.append(f"{indent}{php_str(k)} => array({inner}),")
        else:
            vv = v[2:] if v.startswith("./") else v
            out.append(f"{indent}{php_str(k)} => $baseDir . '/{vv}',")
    return "\n".join(out)


def php_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


os.makedirs(os.path.join(VENDOR, "composer"), exist_ok=True)

with open(os.path.join(VENDOR, "composer", "autoload_psr4.php"), "w") as f:
    f.write("<?php\n\n// autoload_psr4.php @generated by gh-composer\n" + '\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n')
    f.write(php_arr(psr4))
    f.write("\n);\n")

with open(os.path.join(VENDOR, "composer", "autoload_classmap.php"), "w") as f:
    f.write("<?php\n\n// autoload_classmap.php @generated by gh-composer\n" + '\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n')
    f.write(php_arr(classmap))
    f.write("\n);\n")

with open(os.path.join(VENDOR, "composer", "autoload_files.php"), "w") as f:
    f.write("<?php\n\n// autoload_files.php @generated by gh-composer\n" + '\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n')
    for i, fl in enumerate(files):
        fl2 = fl[2:] if fl.startswith("./") else fl
        f.write(f"    '{i:032x}' => $baseDir . '/{fl2}',\n".replace("$baseDir", chr(36)+"baseDir"))
    f.write(");\n")

with open(os.path.join(VENDOR, "composer", "autoload_psr0.php"), "w") as f:
    f.write("<?php\n" + '\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n')
    f.write(php_arr(psr0))
    f.write("\n);\n")

AUTOLOAD = r"""<?php

// autoload.php @generated by gh-composer (Packagist-free installer)

require_once __DIR__ . '/composer/ClassLoader.php';

$loader = new \Composer\Autoload\ClassLoader(dirname(__DIR__));

foreach (require __DIR__ . '/composer/autoload_psr4.php' as $ns => $dirs) {
    $loader->setPsr4($ns, $dirs);
}
foreach (require __DIR__ . '/composer/autoload_psr0.php' as $ns => $dirs) {
    $loader->set($ns, $dirs);
}
$loader->addClassMap(require __DIR__ . '/composer/autoload_classmap.php');
$loader->register(true);

foreach (require __DIR__ . '/composer/autoload_files.php' as $file) {
    if (file_exists($file)) {
        require_once $file;
    }
}

return $loader;
"""
open(os.path.join(VENDOR, "autoload.php"), "w").write(AUTOLOAD)

# Laravel package manifest (replaces `artisan package:discover`)
os.makedirs(os.path.join(ROOT, "bootstrap", "cache"), exist_ok=True)
manifest = "<?php return " + json.dumps(
    {"providers": providers, "aliases": aliases}, indent=1
).replace("{", "array(").replace("}", ")").replace(":", " => ") + ";\n"
# safer: build php array manually
def to_php(v, ind=0):
    sp = " " * ind
    if isinstance(v, dict):
        s = "array(\n"
        for k, val in v.items():
            s += f"{sp}  {php_str(k)} => {to_php(val, ind+2)},\n"
        return s + sp + ")"
    if isinstance(v, list):
        s = "array(\n"
        for val in v:
            s += f"{sp}  {to_php(val, ind+2)},\n"
        return s + sp + ")"
    return php_str(str(v))

open(os.path.join(ROOT, "bootstrap", "cache", "packages.php"), "w").write(
    "<?php return " + to_php(package_manifest) + ";\n")
open(os.path.join(ROOT, "bootstrap", "cache", "services.php"), "w").write(
    "<?php return array('providers' => array(), 'eager' => array(), 'deferred' => array());\n")

print(f"psr4={len(psr4)} classmap={len(classmap)} files={len(files)} providers={len(providers)}")
